#include "NativeSecrets.h"
#include <CommonCrypto/CommonHMAC.h>
#include <string.h>
#include <stdlib.h>
#include <time.h>
#include <stdio.h>

// ---------------------------------------------------------------------------
// Volatile integrity token — checked before every sensitive operation
// ---------------------------------------------------------------------------
static volatile int g_integrity_token = 0x000000;

// ---------------------------------------------------------------------------
// Secure zero — compiler cannot optimize away
// ---------------------------------------------------------------------------
__attribute__((noinline))
static void secureZero(void* ptr, size_t len) {
    volatile unsigned char* p = (volatile unsigned char*)ptr;
    for (size_t i = 0; i < len; i++) {
        p[i] = 0;
    }
}

// ---------------------------------------------------------------------------
// Secure exit — unhookable crash via hardware trap instruction
// ---------------------------------------------------------------------------
__attribute__((noinline, optnone, noreturn))
void NativeSecrets_secureExit(void) {
    // __builtin_trap compiles to brk #1 on ARM64, ud2 on x86
    __builtin_trap();
}

// ---------------------------------------------------------------------------
// 3-layer XOR deobfuscation
// ---------------------------------------------------------------------------
static void deobfuscate(const unsigned char* obfuscated,
                        const unsigned char* maskA,
                        const unsigned char* maskB,
                        size_t len,
                        unsigned char* out,
                        unsigned char coef1,
                        unsigned char coef2) {
    for (size_t i = 0; i < len; i++) {
        out[i] = obfuscated[i] ^ maskA[i] ^ maskB[i] ^ ((unsigned char)((i * coef1 + coef2) & 0xFF));
    }
}

// ---------------------------------------------------------------------------
// Obfuscated HMAC key (iOS-specific, INDEPENDENT from Android)
// Generated by scripts/generate-obfuscated-secret.py
// ---------------------------------------------------------------------------
// Obfuscated HMAC key bytes (iOS-specific, generated by scripts/generate-obfuscated-secret.py)
static const unsigned char HMAC_KEY_OBFUSCATED[32] = {
    0xB4, 0x6C, 0x23, 0xE5, 0x9F, 0x47, 0xDA, 0x10,
    0xC8, 0x2B, 0x74, 0xA9, 0x5E, 0x83, 0xF0, 0x3C,
    0x69, 0xBA, 0x25, 0xE7, 0x08, 0xDC, 0x91, 0x4F,
    0xA3, 0x56, 0x82, 0xCB, 0x1D, 0x70, 0xB4, 0xE9
};
static const unsigned char HMAC_KEY_MASK_A[32] = {
    0x42, 0x3F, 0x9C, 0x54, 0xA7, 0xE1, 0x06, 0x8B,
    0xD4, 0x79, 0xC4, 0x1E, 0x63, 0xF5, 0xB8, 0x2A,
    0x97, 0x4D, 0x00, 0xD6, 0x5B, 0xAF, 0x72, 0xC9,
    0x14, 0x86, 0xEB, 0x3D, 0x90, 0x58, 0xA2, 0x7F
};
static const unsigned char HMAC_KEY_MASK_B[32] = {
    0xD8, 0x05, 0xB9, 0x4A, 0x38, 0xF3, 0x67, 0xCC,
    0x1B, 0x82, 0x5E, 0x70, 0x99, 0x3E, 0xA4, 0xDB,
    0x42, 0x18, 0xFD, 0x2F, 0xC0, 0x64, 0xB5, 0x07,
    0x58, 0xAA, 0x39, 0xE2, 0x5D, 0x9B, 0xCF, 0x43
};
static const unsigned char HMAC_KEY_COEF1 = 0x00;
static const unsigned char HMAC_KEY_COEF2 = 0x00;

// ---------------------------------------------------------------------------
// Obfuscated relay endpoint
// Generated by scripts/generate-obfuscated-secret.py
// ---------------------------------------------------------------------------
// "wss://YOUR_RELAY_URL"
static const unsigned char ENDPOINT_RELAY_OBFUSCATED[] = {
    0xE5, 0x21, 0x21, 0x6A, 0x63, 0x63, 0x8E, 0xB9,
    0xA7, 0xB3, 0xC1, 0x70, 0x9B, 0xB4, 0xC2, 0x7F,
    0xA6, 0xB0, 0xD9, 0xAE, 0x8F, 0xA9, 0xDB, 0x7F,
    0x9D, 0xA0, 0xB8, 0x11
};
static const unsigned char ENDPOINT_RELAY_MASK_A[] = {
    0x92, 0x42, 0x42, 0x0B, 0x00, 0x04, 0xEF, 0xDA,
    0xC4, 0xD0, 0xAE, 0x11, 0xFA, 0xD5, 0xAF, 0x1E,
    0xC7, 0xD1, 0xBC, 0xCF, 0xEC, 0xCA, 0xBC, 0x1E,
    0xFA, 0xC1, 0xDB, 0x72
};
static const unsigned char ENDPOINT_RELAY_MASK_B[] = {
    0x57, 0x87, 0x87, 0xCE, 0xC5, 0xC5, 0x2A, 0x1F,
    0x01, 0x15, 0x6D, 0xD4, 0x3F, 0x10, 0x62, 0xDB,
    0x02, 0x14, 0x7D, 0x0A, 0x2B, 0x0D, 0x7F, 0xDB,
    0x3D, 0x04, 0x1C, 0xB7
};
static const unsigned char ENDPOINT_RELAY_COEF1 = 0x00;
static const unsigned char ENDPOINT_RELAY_COEF2 = 0x00;

// ---------------------------------------------------------------------------
// Obfuscated SPKI certificate pin hashes
// ---------------------------------------------------------------------------
static const char CERT_PIN_LEAF[] = "sha256/PLACEHOLDER_PIN_HASH";
static const char CERT_PIN_INTERMEDIATE[] = "sha256/PLACEHOLDER_PIN_HASH";
static const char CERT_PIN_ROOT[] = "sha256/PLACEHOLDER_PIN_HASH";

// ---------------------------------------------------------------------------
// Hex encoding helper
// ---------------------------------------------------------------------------
static void hex_encode(const unsigned char* data, size_t len, char* out) {
    static const char hex[] = "0123456789abcdef";
    for (size_t i = 0; i < len; i++) {
        out[i*2]   = hex[(data[i] >> 4) & 0x0F];
        out[i*2+1] = hex[data[i] & 0x0F];
    }
    out[len*2] = '\0';
}

// ---------------------------------------------------------------------------
// Generate MAC for a data string using CommonCrypto
// ---------------------------------------------------------------------------
static void generateMAC(const char* data, char macOutput[65]) {
    if (g_integrity_token != 0x000000) {
        NativeSecrets_secureExit();
    }

    unsigned char key[32];
    deobfuscate(HMAC_KEY_OBFUSCATED, HMAC_KEY_MASK_A, HMAC_KEY_MASK_B,
                32, key, HMAC_KEY_COEF1, HMAC_KEY_COEF2);

    unsigned char mac[CC_SHA256_DIGEST_LENGTH];
    CCHmac(kCCHmacAlgSHA256, key, 32, data, strlen(data), mac);
    hex_encode(mac, CC_SHA256_DIGEST_LENGTH, macOutput);

    secureZero(key, 32);
    secureZero(mac, CC_SHA256_DIGEST_LENGTH);
}

// ---------------------------------------------------------------------------
// Inline hook detection (architecture-guarded)
// ---------------------------------------------------------------------------
static int checkInlineHooks(void) {
#if defined(__aarch64__)
    void* funcAddr = (void*)checkInlineHooks;
    unsigned char* bytes = (unsigned char*)funcAddr;

    // ARM64: LDR X16, #8; BR X16 = Frida/Substrate trampoline pattern
    if (bytes[0] == 0x50 && bytes[1] == 0x00 &&
        bytes[2] == 0x00 && bytes[3] == 0x58) {
        return 1;
    }

    // ARM64: ADRP + BR X16/X17 — another common trampoline
    // Check for BR X16 (0xD61F0200) or BR X17 (0xD61F0220)
    uint32_t insn;
    memcpy(&insn, bytes + 4, 4);
    if (insn == 0xD61F0200 || insn == 0xD61F0220) {
        return 1;
    }

    return 0;
#elif defined(__arm__)
    void* funcAddr = (void*)checkInlineHooks;
    unsigned char* bytes = (unsigned char*)funcAddr;
    if (bytes[3] == 0xE5 && bytes[2] == 0x9F && bytes[1] == 0xF0) {
        return 1;
    }
    return 0;
#else
    // x86/x86_64 (simulators) — skip hook detection
    return 0;
#endif
}

// ---------------------------------------------------------------------------
// Free a result string
// ---------------------------------------------------------------------------
void NativeSecrets_freeResult(char* result) {
    if (result) {
        size_t len = strlen(result);
        volatile char* p = (volatile char*)result;
        for (size_t i = 0; i < len; i++) { p[i] = 0; }
        free(result);
    }
}

// ---------------------------------------------------------------------------
// Sign a security result
// Returns: malloc'd "STATUS:details:timestamp:hmac_hex"
// ---------------------------------------------------------------------------
char* NativeSecrets_signSecurityResult(const char* status) {
    if (g_integrity_token != 0x000000) {
        NativeSecrets_secureExit();
    }

    char payload[512];
    long timestamp = (long)time(NULL);
    snprintf(payload, sizeof(payload), "%s:%ld", status, timestamp);

    char mac[65];
    generateMAC(payload, mac);

    size_t resultLen = strlen(payload) + 1 + 64 + 1;
    char* result = (char*)malloc(resultLen);
    if (!result) return NULL;
    snprintf(result, resultLen, "%s:%s", payload, mac);

    return result;
}

// ---------------------------------------------------------------------------
// Enforce a signed security result (crashes on failure)
// ---------------------------------------------------------------------------
void NativeSecrets_enforceSecurityResult(const char* signedResult) {
    if (g_integrity_token != 0x000000) {
        NativeSecrets_secureExit();
    }

    // Parse: find last ':' which separates the HMAC from the payload
    const char* lastColon = strrchr(signedResult, ':');
    if (!lastColon || lastColon == signedResult) {
        NativeSecrets_secureExit();
    }

    size_t payloadLen = (size_t)(lastColon - signedResult);
    char payload[512];
    if (payloadLen >= sizeof(payload)) {
        NativeSecrets_secureExit();
    }
    memcpy(payload, signedResult, payloadLen);
    payload[payloadLen] = '\0';

    const char* providedMAC = lastColon + 1;

    char expectedMAC[65];
    generateMAC(payload, expectedMAC);

    // Constant-time comparison
    int diff = 0;
    if (strlen(providedMAC) != 64) {
        diff = 1;
    } else {
        for (int i = 0; i < 64; i++) {
            diff |= providedMAC[i] ^ expectedMAC[i];
        }
    }

    // Check timestamp freshness (< 30 seconds)
    if (diff == 0) {
        const char* tsColon = strrchr(payload, ':');
        if (tsColon) {
            long ts = atol(tsColon + 1);
            long now = (long)time(NULL);
            if (now - ts > 300 || ts - now > 30) {
                diff = 1;
            }
        } else {
            diff = 1;
        }
    }

    secureZero(payload, sizeof(payload));
    secureZero(expectedMAC, 65);

    if (diff != 0) {
        NativeSecrets_secureExit();
    }

    if (checkInlineHooks()) {
        NativeSecrets_secureExit();
    }
}

// ---------------------------------------------------------------------------
// Verify certificate pin — returns malloc'd signed result
// ---------------------------------------------------------------------------
char* NativeSecrets_verifyCertificatePin(const char* spkiHash) {
    if (g_integrity_token != 0x000000) {
        NativeSecrets_secureExit();
    }

    const char* status;
    if (strcmp(spkiHash, CERT_PIN_LEAF) == 0 ||
        strcmp(spkiHash, CERT_PIN_INTERMEDIATE) == 0 ||
        strcmp(spkiHash, CERT_PIN_ROOT) == 0) {
        status = "VALID";
    } else {
        status = "INVALID";
    }

    char payload[256];
    long timestamp = (long)time(NULL);
    snprintf(payload, sizeof(payload), "%s:%ld", status, timestamp);

    char mac[65];
    generateMAC(payload, mac);

    size_t resultLen = strlen(payload) + 1 + 64 + 1;
    char* result = (char*)malloc(resultLen);
    if (!result) return NULL;
    snprintf(result, resultLen, "%s:%s", payload, mac);

    return result;
}

// ---------------------------------------------------------------------------
// Get deobfuscated endpoint URL — returns malloc'd string
// ---------------------------------------------------------------------------
char* NativeSecrets_getEndpoint(const char* key) {
    if (g_integrity_token != 0x000000) {
        NativeSecrets_secureExit();
    }

    if (strcmp(key, "relay") == 0) {
        size_t len = sizeof(ENDPOINT_RELAY_OBFUSCATED);
        unsigned char deobfuscated[256];
        deobfuscate(ENDPOINT_RELAY_OBFUSCATED, ENDPOINT_RELAY_MASK_A,
                     ENDPOINT_RELAY_MASK_B, len, deobfuscated,
                     ENDPOINT_RELAY_COEF1, ENDPOINT_RELAY_COEF2);

        char* result = (char*)malloc(len + 1);
        if (!result) {
            secureZero(deobfuscated, sizeof(deobfuscated));
            return NULL;
        }
        memcpy(result, deobfuscated, len);
        result[len] = '\0';
        secureZero(deobfuscated, sizeof(deobfuscated));
        return result;
    }

    return NULL;
}
